- name: install dotfiles dependencies
  when: ansible_os_family == "RedHat"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
   - bc
   - tmux
   - automake
   - bison
   - bzip2
   - bzip2-devel
   - cmake
   - vim
   - curl
   - gcc
   - sudo
   - gcc-c++
   - git
   - glibc-devel
   - kernel-devel
   - make
   - openssl-devel
   - python-devel
   - readline-devel
   - sqlite
   - sqlite-devel
   - zlib-devel
   - zsh
   - rsync

- name: install dotfiles dependencies
  when: ansible_os_family == "Debian"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
   - bc
   - binutils
   - bison
   - build-essential
   - sudo
   - vim
   - cmake
   - curl
   - gcc
   - git
   - libbz2-dev
   - libncurses5-dev
   - libncursesw5-dev
   - libreadline-dev
   - libsqlite3-dev
   - libssl-dev
   - llvm
   - make
   - mercurial
   - python-dev
   - python3-dev
   - wget
   - xz-utils
   - zlib1g-dev
   - zsh
   - tmux
   - rsync
