
- name: ensure a list of packages installed
  when: ansible_os_family == "RedHat"
  package:
    name: "{{ packages }}"
  vars:
    packages:
     - autoconf
     - automake
     - bc
     - bison
     - bzip2
     - bzip2-devel
     - cmake
     - curl
     - gcc
     - gcc-c++
     - git
     - glibc-devel
     - kernel-devel
     - libtool
     - make
     - ninja-build
     - openssl-devel
     - pkgconfig
     - python-devel
     - readline-devel
     - rsync
     - sqlite
     - sqlite-devel
     - sudo
     - tmux
     - unzip
     - vim
     - zlib-devel
     - zsh

- name: ensure a list of packages installed
  when: ansible_os_family == "Debian"
  package:
    name: "{{ packages }}"
  vars:
    packages:
     - bc
     - binutils
     - bison
     - build-essential
     - sudo
     - vim
     - cmake
     - curl
     - gcc
     - git
     - libbz2-dev
     - libncurses5-dev
     - libncursesw5-dev
     - libreadline-dev
     - libsqlite3-dev
     - libssl-dev
     - llvm
     - make
     - mercurial
     - python-dev
     - python3-dev
     - wget
     - xz-utils
     - zlib1g-dev
     - zsh
     - tmux
     - rsync
