---


- fail:
    msg: "Variable 'dotfiles_username' is not defined or empty"
  when: ((dotfiles_username is undefined) or (dotfiles_username is none) or (dotfiles_username | trim == ''))

- include_tasks: dotfiles.yml

